export const ActionTypes = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  ADJUST_QTY: "ADJUST_QTY",
  ADD_TO_FAVORITE: "ADD_TO_FAVORITE",
  REMOVE_FROM_FAVORITE: "REMOVE_FROM_FAVORITE",
};
